services:
  app:
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    restart: always
    env_file: .mongo.env
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    env_file: .mongo.env
    ports:
      - 8080:8081
    depends_on:
      - mongodb

volumes:
  mongo_data:
